### ISSUE TITLE
sdmpy and telcal

### ISSUE THREAD

**Issue by caseyjlaw** [demorest/sdmpy#10]
I see that sdmpy has a calibration procedure built in. Separately, we use telcal solutions in realfast. In the future, gain solutions will need to be released along with realfast data, so some thinking is needed about standardization. 
If we think of this as a set of tools pure-Python data analysis, then:
- sdmpy is the data input/output library,
- telcal should be a new calibration parsing library,
- their internal data structures should be somewhat aligned, and
- maybe sdmpy calibration should also be aligned with the telcal data structure.

I don't really want to commit to building a new CASA, but these low-level tools would support us directly and if released via pip they could serve the community.

What do you think?

**Comment by demorest** [comment]
Few thoughts/comments about this:

The calibration stuff in sdmpy is not currently meant for "production" use but has been useful for me debugging datasets that CASA doesn't yet support (mainly binning mode).  Of course that doesn't mean it can't be expanded into something more generally useful.

What I've sometimes thought about making is some kind of lightweight data structure for representing visibility data in python.  sdmpy gives simple numpy arrays which are very useful, but can lead to some kludgey code, eg you need to know/hardcode which array axis is time/freq/whatever.  This data structure could be part of a library that includes functionality for representing/applying calibration solutions (from various sources), could be eventually extended as needed to also solve for solutions, etc.  

I've usually thought about building this in to sdmpy but I agree that modularity is good so maybe it should be a separate library.  We should definitely _not_ call it "telcal" though.. that name is already overused and it would just add confusion.

I think key to all this is getting a good data structure designed.  I've had a few thoughts on this.. something closer to numpy arrays (rather than CASA-style tables) is probably a good idea.  If this all sounds good to you maybe I can sketch out some basic design and then we can iterate a bit?

**Comment by caseyjlaw** [comment]
Glad to hear you've been thinking about this already. I'd be happy to see details when you have time.
FWIW, I've heard good things about this library for labeled N-dimensional data in Python: https://github.com/pydata/xarray. It would add some features that enable data inspection and manipulation, but preserves vectorized operations of numpy.

**Comment by demorest** [comment]
Thanks for the pointer to xarray, it looks really useful and seems to have many of the features I'd like for this!  The only thing that gives me slight pause is the dependence on pandas but it might be worth it in this case.  I'll play around a bit and see how it goes.

On the topic of dependencies, do you have any opinions on astropy?  I've used it in other contexts and it has some functionality that could be very useful here (physical units, time/coordinate conversions, etc) but it's also kind of big/bloaty (IMO anyway).

**Comment by caseyjlaw** [comment]
I'd think pandas is a pretty safe dependency to add, given its community support.
I have been using astropy and dask more recently. rfpipe (next-gen rtpipe) depends on both of those in the current design. astropy is big, but they try to control that by pushing non-core features into "affiliated packages". Adam Ginsberg has made one, so he could tell you more.

**Comment by demorest** [comment]
Hi Casey, I'm going to close this issue.  I still think a lightweight visibility/calibration handling library is a good idea, but probably should be implemented as a separate library, not as part of sdmpy.
